# Generated by Django 4.1 on 2022-10-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('desc_estado', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('motivoingreso', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('idprofesiones', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_profesion', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('rut', models.CharField(db_column='RUT', max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('numregistro', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=255, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('profesiones_idprofesiones', models.ForeignKey(db_column='profesiones_idprofesiones', on_delete=django.db.models.deletion.DO_NOTHING, to='main.profesiones')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('nficha', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('pacientes_rut', models.ForeignKey(db_column='pacientes_rut', on_delete=django.db.models.deletion.DO_NOTHING, to='main.pacientes')),
                ('profesionales_rut', models.ForeignKey(db_column='profesionales_RUT', on_delete=django.db.models.deletion.DO_NOTHING, to='main.profesionales')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('idcomentarios', models.IntegerField(primary_key=True, serialize=False)),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('nficha', models.ForeignKey(db_column='nficha', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('estado_idestado', models.ForeignKey(db_column='estado_idestado', on_delete=django.db.models.deletion.DO_NOTHING, to='main.estado')),
                ('pacientes_rut', models.ForeignKey(db_column='pacientes_rut', on_delete=django.db.models.deletion.DO_NOTHING, to='main.pacientes')),
                ('profesionales_rut', models.ForeignKey(db_column='profesionales_RUT', on_delete=django.db.models.deletion.DO_NOTHING, to='main.profesionales')),
            ],
        ),
    ]
