# Generated by Django 4.1 on 2022-10-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionales',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
