# Generated by Django 4.1 on 2022-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profesionales_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='motivoingreso',
        ),
        migrations.AddField(
            model_name='ficha',
            name='motivoingreso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
