# Generated by Django 4.1 on 2022-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_pacientes_motivoingreso_ficha_motivoingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='idregistro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
