# Generated by Django 4.1 on 2022-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_registro_created_at_alter_registro_idregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
