# Generated by Django 4.1 on 2022-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_registro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
